farms/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views


app_name = 'farms'
urlpatterns = [
    # Hawaiian Soil Urls
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('farm/', views.farm, name='farm'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    # path('form/', views.profile_form, name='profile_form'),


    # Registration Urls
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
]

hawaiiansoil/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url


#admin.autodiscover()

urlpatterns = [
    path('', include('farms.urls', namespace='farms')),
    path('admin/', admin.site.urls),
]

farms/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
#from django.contrib.auth.models import User

from django.core.validators import RegexValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

from localflavor.us.models import USStateField, USZipCodeField

import datetime


YEAR_CHOICES = []
for r in range(1980, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r,r))




# Create your models here.
class Farmer(AbstractUser):

    def __str__(self):
        return self.first_name + " " + self.last_name

    # Fields in the AbstractUser
    # username = models.CharField(max_length=30, unique=True)
    # password = models.CharField(max_length=30)
    # first_name = models.CharField(max_length=50, blank=True)
    # last_name = models.CharField(max_length=50, blank=True)
    # email = models.EmailField(blank=True)
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    street_address = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=30, blank=True)
    state = USStateField(blank=True)
    zipcode = USZipCodeField(blank=True)

    # bio = models.TextField(max_length=500, blank=True)
    # location = models.CharField(max_length=30, blank=True)
    # birth_date = models.DateField(null=True, blank=True)


@receiver(post_save, sender=AbstractUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Farmer.objects.create(user=instance)


@receiver(post_save, sender=AbstractUser)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


@receiver(post_save, sender=AbstractUser)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Farmer.objects.create(user=instance)
    instance.profile.save()


class Farm(models.Model):

    def __str__(self):
        return self.farm_name

    username = models.ForeignKey(Farmer, to_field='username', on_delete=models.CASCADE)
    farm_name = models.CharField(max_length=50)
    street_address =  models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=30, blank=True)
    state = USStateField(blank=True)
    zipcode = USZipCodeField(blank=True)
    owned_since = models.IntegerField(choices=YEAR_CHOICES, default=datetime.datetime.now().year, blank=True)
    main_crop = models.CharField(max_length=50, blank=True)
    ownership_type = models.CharField(max_length=50, blank=True)
    acres = models.IntegerField(blank=True)

farms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from localflavor.us.forms import USStateSelect
# from django.core.exceptions import ValidationError
# from django.utils.translation import ugettext_lazy as _
from farms.models import Farmer, Farm


class SignUpForm(UserCreationForm):

    class Meta:
        model = Farmer
        fields = [
            'username',
            'password1',
            'password2',
        ]


class ProfileForm(forms.ModelForm):

    state = forms.CharField(widget=USStateSelect(), initial='HI')

    class Meta:
        model = Farmer
        fields = [
            'first_name', 'last_name',
            'email', 'phone_number',
            'street_address',
            'city', 'state', 'zipcode',
        ]


class FarmForm(forms.ModelForm):

    state = forms.CharField(widget=USStateSelect(), initial='HI')

    class Meta:
        model = Farm
        fields = [
            'farm_name',
            'street_address',
            'city', 'state', 'zipcode',
            'main_crop', 'acres',
            'owned_since', 'ownership_type',
        ]



# class AlertForm(forms.Form):
#
#     validation_text = forms.CharField(
#         label='',
#         max_length=15,
#     )
#
#     def __init__(self, *args, **kwargs):
#         self.send_text = kwargs.pop('send_text')
#         super(AlertForm, self).__init__(*args, **kwargs)
#         self.fields['validation_text'].widget = forms.TextInput(
#             attrs = {
#                 'placeholder': self.send_text
#             }
#         )
#
#     def clean_validation_text(self):
#         validation_text = self.cleaned_data['validation_text']
#         print(self.send_text)
#         if validation_text != self.send_text:
#             raise forms.ValidationError("Incorrect verification message!")
#         return validation_text
#
#
#
#


farms/views.py
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from farms.forms import SignUpForm, ProfileForm, FarmForm


base_context = {
    'title': 'Hawaiian Soil',
    'crops': ['Potatoes', 'Tomatoes', 'Spinach'],
}


def index(request):
    template_path = 'farms/index.html'
    context = base_context
    return render(request, template_path, context)


@login_required
def home(request):
    template_path = 'farms/home.html'
    context = base_context
    return render(request, template_path, context)


@login_required
def farm(request):
    template_path = 'farms/farm.html'
    # Upon submission / a POST request from the Farm form
    if request.method == 'POST':
        form = FarmForm(data=request.POST)

        # Check if the form is valid with the model constraints
        print("Form is valid?: " + str(form.is_valid()))
        if form.is_valid():
            farm = form.save(commit=False)  # Save the data from the signup
            if farm.username is None:
                farm.username = request.user.get_username()
                print("Added username to " + farm.farm_name)
            farm.refresh_from_db()  # load the profile instance created by the signal
            farm.save()
            return redirect('/')  # Redirect the user to the home page
    # Request was probably a GET request and the user wants to see the form
    else:
        form = FarmForm()
    # Set context to the base
    context = base_context
    context['form'] = form
    return render(request, template_path, context)



@login_required
def profile(request):
    template_path = 'farms/profile.html'
    # Upon submission / a POST request from the SignUpForm
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user)

        # Check if the form is valid with the model constraints
        if form.is_valid():
            user = form.save()  # Save the data from the signup
            user.refresh_from_db()  # load the profile instance created by the signal
            user.save()

            return redirect('/')  # Redirect the user to the home page
        print(form.is_valid())
    # Request was probably a GET request and the user wants to see the form
    else:
        form = ProfileForm()
    # Set context to the base
    context = base_context
    context['form'] = form
    return render(request, template_path, context)



def about(request):
    template_path = 'farms/about.html'
    context = {
        'title': "Hawaiian Soil",
        'crops': ['Potatoes', 'Tomatoes', 'Spinach'],
    }
    return render(request, template_path, context)


def signup(request):
    template_path = 'registration/signup.html'

    # Upon submission / a POST request from the SignUpForm
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        # Check if the form is valid with the model constraints
        if form.is_valid():
            user = form.save()      # Save the data from the signup
            user.refresh_from_db()  # load the profile instance created by the signal
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)    # Login the user to their new account
            return redirect('/')   # Redirect the user to the home page
    # Request was probably a GET request and the user wants to see the form
    else:
        form = SignUpForm()
    # Set context to the base
    context = base_context
    context['form'] = form
    return render(request, template_path, context)


# def login(request):
#     template_path = 'farms/login.html'
#
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         # Check if the form is valid with the model constraints
#         if form.is_valid():
#             user = form.save()  # Save the data from the signup
#             #user.refresh_from_db()  # load the profile instance created by the signal
#             user = authenticate(request, username=user.username, password=user.password)
#             if user is not None:
#                 login(request, user)  # Login the user to their new account
#             return redirect('..')  # Redirect the user to the home page
#     else:
#         form = LoginForm()
#     context = {
#         'title': "Hawaiian Soil",
#         'crops': ['Potatoes', 'Tomatoes', 'Spinach'],
#         'form': form,
#     }
#     return render(request, template_path, context)

farms/templates/farms/about.html
{% extends "farms/base.html" %}
{% block content %}

{% endblock %}

farms/templates/farms/base.html
{% load static %}
<!DOCTYPE html>
{# Make modifiable head elements #}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1,user-scalable=no">

    <title>Hawaiian Soil</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css">
    <link rel="stylesheet" href="https://js.arcgis.com/4.6/esri/css/main.css">
    <link rel="stylesheet" href="{% static "farms/style.css" %}">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.js"></script>
    <script src="https://js.arcgis.com/4.6/"></script>
    <script type="text/javascript" src="{% static "farms/farm_gis.js" %}"></script>

    <script>
        $('.ui .item').on('click', function() {
            $('.ui .item').removeClass('active');
            $(this).addClass('active');
        });
    </script>
</head>
<div id="site-wrapper">
    <header>
        <div class="ui inverted vertical center aligned segment">
            <div class="ui large inverted pointing menu">
                <div class="item">
                    <img src="{% static "farms/manoaseal.png" %}">
                </div>
                {# Left side of Menu with different page listings #}
                <a class="header item" href="{% url "farms:index" %}">Hawaiian Soil</a>
                <a class="item" href="{% url "farms:home" %}">Home</a>
                <a class="item" href="{% url "farms:farm" %}">Farms</a>
                <a class="item" href="{% url "farms:profile" %}">Profile</a>
                <a class="item" href="{% url "farms:about" %}">How to Use</a>
                {# Right Side of Menu with login info #}
                <div class="right menu">
                    {# If the user is logged in, display their username and a logout button #}
                    {% if user.is_authenticated %}
                        <div class="item">
                            You are logged in as: {{ user.username }}
                        </div>
                        <div class="item">
                            <a class="ui button" href="{% url "farms:logout" %}">Log Out</a>
                        </div>
                        {# If the user is not logged in, display the signup and login buttons #}
                    {% else %}
                        <div class="item">
                            <a class="ui primary button" href="{% url "farms:signup" %}">Sign Up</a>
                        </div>
                        <div class="item">
                            <a class="ui button" href="{% url "farms:login" %}">Log In</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    <body>
    {# The Document Body #}
    <div id="body-wrapper">
        {% block content %}
            if you see this, something is wrong!
        {% endblock content %}
    </div>
    {# The Footer #}
    <footer>
        <div id="footer-wrapper" class="footer">
            <div class="ui inverted vertical footer segment">
                <div class="ui container">
                    <div class="ui stackable inverted divided equal height stackable grid">
                        <div class="four wide column">
                            <h4 class="ui inverted header">About</h4>
                            <div class="ui inverted link list">
                                <a href="#" class="item">Sitemap</a>
                                <a href="#" class="item">Contact Us</a>
                            </div>
                        </div>
                        <div class="four wide column">
                            <h4 class="ui inverted header">Services</h4>
                            <div class="ui inverted link list">
                            </div>
                        </div>
                        <div class="four wide column">
                            <h4 class="ui inverted header">Hawaiian Soil</h4>
                            <p>2018 University of Hawaii at Manoa</p>
                        </div>
                        <div class="four wide column">
                            <img id="manoaseal" src="{% static "farms/manoaseal.png" %}" style="width: 25%">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    </body>
</div>
</html>

farms/templates/farms/farm.html
{% extends "farms/base.html" %}
{% load widget_tweaks %}
{% block content %}

    {# Load Bootstap Package #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <div class="ui text container segment" style="padding-top: 2em">
        <div class="ui centered huge dividing header">
            Farm
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="card border-success mb-3">
                <div class="card-body">
                    {{ form.errors }}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label>Farm Name</label>
                            {% render_field form.farm_name class="form-control" placeholder="John and Joe Farm of Crops" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label>Address</label>
                            {% render_field form.street_address class="form-control" placeholder="1234 Example Street Apt 101" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>City</label>
                            {% render_field form.city class="form-control" placeholder="City" %}
                        </div>
                        <div class="form-group col-md-4">
                            <label>State</label>
                            {% render_field form.state class="form-control" placeholder="State" %}

                        </div>
                        <div class="form-group col-md-2">
                            <label>Zipcode</label>
                            {% render_field form.zipcode class="form-control" placeholder="96419" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Main Crop</label>
                            {% render_field form.main_crop class="form-control" placeholder="Potatoes" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label>Acres</label>
                            {% render_field form.acres class="form-control" placeholder="20" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Owned Since</label>
                            {% render_field form.owned_since class="form-control" placeholder="1970" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label>Ownership Type</label>
                            {% render_field form.ownership_type class="form-control" placeholder="Lease" %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer text-center">
                <button type="submit" class="btn btn-primary btn-lg">Update Information</button>
            </div>
        </form>
    </div>



{% endblock %}

farms/templates/farms/home.html
{% extends 'farms/base.html' %}
{% block content %}

    <div id="homepage" class="ui centered stackable divided equal height grid">
        <div class="five wide column">
            <div class="ui card">

            </div>
        </div>
        <div class="three wide column">
        </div>
        <div class="eight wide column">
            <div id="viewDiv">
                <div id="draw-polygon" class="esri-widget-button esri-widget esri-interactive" title="Draw and measure polygon">
                    <span class="esri-icon-polygon"></span>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

farms/templates/farms/index.html
{% extends 'farms/base.html' %}
{% block content %}

    <div class="ui centered stackable divided equal height grid">
        <div class="five wide column">
            <div class="ui card">

            </div>
        </div>
        <div class="three wide column">
        </div>
        <div class="eight wide column">
            <div id="viewDiv">
                <div id="draw-polygon" class="esri-widget-button esri-widget esri-interactive" title="Draw and measure polygon">
                    <span class="esri-icon-polygon"></span>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{#    <div class="container">#}
{#        <form>#}
{#            <div class="card border-success mb-3">#}
{#                <h1 class="card-header text-center ">Farmer Profile Form</h1>#}
{#                <div class="card-body">#}
{#                    <div class="form-row">#}
{#                        <div class="form-group col-md-6">#}
{#                            <label for="inputFirstName">First Name</label>#}
{#                            <input type="text" class="form-control" id="inputFirstName" placeholder="John">#}
{#                        </div>#}
{#                        <div class="form-group col-md-6">#}
{#                            <label for="inputLastName">Last Name</label>#}
{#                            <input type="text" class="form-control" id="inputLastName" placeholder="Smith">#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="form-row">#}
{#                        <div class="form-group col-md-6">#}
{#                            <label for="inputEmail4">Email</label>#}
{#                            <input type="email" class="form-control" id="inputEmail4" placeholder="Email">#}
{#                        </div>#}
{#                        <div class="form-group col-md-6">#}
{#                            <label for="inputPassword4">Phone Number</label>#}
{#                            <input type="tel" class="form-control" id="inputPassword4" placeholder="(808) 123-0054">#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="form-row">#}
{#                        <div class="form-group col-md-6">#}
{#                            <label for="inputAddress">Address</label>#}
{#                            <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">#}
{#                        </div>#}
{#                        <div class="form-group col-md-6">#}
{#                            <label for="inputAddress2">Address 2</label>#}
{#                            <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="form-row">#}
{#                        <div class="form-group col-md-6">#}
{#                            <label for="inputCity">City</label>#}
{#                            <input type="text" class="form-control" id="inputCity">#}
{#                        </div>#}
{#                        <div class="form-group col-md-4">#}
{#                            <label for="inputState">State</label>#}
{#                            <select id="inputState" class="form-control">#}
{#                                <option selected>Choose...</option>#}
{#                                <option>...</option>#}
{#                            </select>#}
{#                        </div>#}
{#                        <div class="form-group col-md-2">#}
{#                            <label for="inputZip">Zip</label>#}
{#                            <input type="text" class="form-control" id="inputZip">#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="card-footer text-center">#}
{#                    <button type="submit" class="btn btn-primary btn-lg">Update Information</button>#}
{#                </div>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}


{# Display a form #}
{#<form action="/url/to/submit/" method="post" class="form">#}
{#  {% csrf_token %}#}
{#  {% bootstrap_form form %}#}
{#  {% buttons %}#}
{#    <button type="submit" class="btn btn-primary">#}
{#      {% bootstrap_icon "star" %} Submit#}
{#    </button>#}
{#  {% endbuttons %}#}
{#</form>#}

{# Read the documentation for more information #}
{# Display farmer form #}


{#<form role="form" method="post" class="form">#}
{#    {% csrf_token %}#}
{#    {% bootstrap_form form %}#}
{#    {% buttons %}#}
{#        <button type="submit" class="btn btn-primary">Submit</button>#}
{#    {% endbuttons %}#}
{#</form>#}

farms/templates/farms/profile.html
{% extends 'farms/base.html' %}
{% load widget_tweaks %}
{% block content %}

    {# Load Bootstap Package #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <div class="ui text container segment" style="padding-top: 2em">
        <div class="ui centered huge dividing header">
            Profile
        </div>
        <form method="post">
            {{ form.errors }}
            {{ form.non_field_errors }}
            {% csrf_token %}
            <div class="card border-success mb-3">
                {#                <h3 class="card-header text-center ">Basic Information</h3>#}
                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>First Name</label>
                            {% render_field form.first_name class="form-control" placeholder="John" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label>Last Name</label>
                            {% render_field form.last_name class="form-control" placeholder="Smith" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Email</label>
                            {% render_field form.email class="form-control" placeholder="example@gmail.com" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label>Phone Number</label>
                            {% render_field form.phone_number class="form-control" placeholder="+123456789" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label>Address</label>
                            {% render_field form.street_address class="form-control" placeholder="1234 Example Street Apt 101" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>City</label>
                            {% render_field form.city class="form-control" placeholder="City" %}
                        </div>
                        <div class="form-group col-md-4">
                            <label>State</label>
                            {% render_field form.state class="form-control" placeholder="State" %}
                        </div>
                        <div class="form-group col-md-2">
                            <label>Zipcode</label>
                            {% render_field form.zipcode class="form-control" placeholder="96419" %}
                        </div>
                    </div>
                </div>
            </div>
            {#            <div class="card border-success mb-3">#}
            {#                <h3 class="card-header text-center ">Farmer Information</h3>#}
            {#                <div class="card-body">#}
            {##}
            {#                    <div class="form-row">#}
            {##}
            {#                    </div>#}
            {#                </div>#}
            {#            </div>#}
            <div class="card-footer text-center">
                <button type="submit" class="btn btn-primary btn-lg">Update Information</button>
            </div>
        </form>
    </div>

{% endblock %}

farms/templates/farms/signup.html
{% extends 'farms/base.html' %}
{% block content %}

    {# Load Bootstap Package #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <div class="ui text container segment" style="padding: 2em;">
        <div class="ui centered huge dividing header">
            Sign Up
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="card-footer text-center">
                <button type="submit" class="btn btn-primary btn-lg">Update Information</button>
            </div>
        </form>
    </div>
{% endblock %}